import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Боковое меню собирается само по дереву папок в docs/.
 * Порядок задают числовые префиксы в именах (01-, 02-, ...); из адресов
 * страниц они вырезаются. Названия разделов лежат в _category_.json.
 */
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
