using System.Buffers;
using McProtoNet.NBT;
using McProtoNet.Protocol;
using McProtoNet.Primitives;
using ConfigCb = McProtoNet.Protocol.Packets.Configuration.Clientbound;
using ConfigSb = McProtoNet.Protocol.Packets.Configuration.Serverbound;
using LoginSb = McProtoNet.Protocol.Packets.Login.Serverbound;
using PlaySb = McProtoNet.Protocol.Packets.Play.Serverbound;

namespace McProtoNet.Tests.Protocol;

/// <summary>
/// Round-trip tests for the C# sources generated by minecraft-protocol-fs and delivered into
/// src/McProtoNet.Protocol/Generated. Exercises the real McProtoNet.Primitives API end to end:
/// write a generated packet, read it back, and check the result matches (plus GetPacketId against
/// the fs packet-id manifest, Spec/protocol-ids.json).
/// </summary>
public class GeneratedRoundTripTests
{
    private static T RoundTrip<T>(T value, int pv) where T : IProtocolType<T>
    {
        var writer = new MinecraftPrimitiveWriter();
        value.Write(writer, pv);
        using var mem = writer.GetWrittenMemory();
        var reader = new MinecraftPrimitiveReader(new ReadOnlySequence<byte>(mem.Memory));
        return T.Read(ref reader, pv);
    }

    // ── Configuration KeepAlive ───────────────────────────────────────────────

    [Theory]
    [InlineData(764)]
    [InlineData(772)]
    public void ConfigurationKeepAlive_Clientbound_RoundTrips(int pv)
    {
        var p = new ConfigCb.KeepAlivePacket(123456789L);
        var back = RoundTrip(p, pv);
        Assert.Equal(p, back);
    }

    [Theory]
    [InlineData(764)]
    [InlineData(772)]
    public void ConfigurationKeepAlive_Serverbound_RoundTrips(int pv)
    {
        var p = new ConfigSb.KeepAlivePacket(-987654321L);
        var back = RoundTrip(p, pv);
        Assert.Equal(p, back);
    }

    // ── Configuration Ping / Pong ─────────────────────────────────────────────

    [Fact]
    public void ConfigurationPing_764_RoundTrips()
    {
        var p = new ConfigCb.PingPacket(42);
        var back = RoundTrip(p, 764);
        Assert.Equal(p, back);
    }

    [Fact]
    public void ConfigurationPong_764_RoundTrips()
    {
        var p = new ConfigSb.PongPacket(42);
        var back = RoundTrip(p, 764);
        Assert.Equal(p, back);
    }

    // ── Configuration SelectKnownPacks ────────────────────────────────────────
    // KnownPack[] / KnownPack are plain classes with no value equality, so compare field by field.

    private static void AssertPacksEqual(KnownPack[] expected, KnownPack[] actual)
    {
        Assert.Equal(expected.Length, actual.Length);
        for (int i = 0; i < expected.Length; i++)
        {
            Assert.Equal(expected[i].Namespace, actual[i].Namespace);
            Assert.Equal(expected[i].Id, actual[i].Id);
            Assert.Equal(expected[i].Version, actual[i].Version);
        }
    }

    [Theory]
    [InlineData(766)]
    [InlineData(772)]
    public void SelectKnownPacks_Clientbound_TwoPacks_RoundTrips(int pv)
    {
        var packs = new[]
        {
            new KnownPack("minecraft", "core", "1.21"),
            new KnownPack("minecraft", "chat_type", "1.21"),
        };
        var p = new ConfigCb.SelectKnownPacksPacket(packs);
        var back = RoundTrip(p, pv);
        AssertPacksEqual(packs, back.Packs);
    }

    [Theory]
    [InlineData(766)]
    [InlineData(772)]
    public void SelectKnownPacks_Clientbound_EmptyArray_RoundTrips(int pv)
    {
        var p = new ConfigCb.SelectKnownPacksPacket([]);
        var back = RoundTrip(p, pv);
        Assert.Empty(back.Packs);
    }

    [Theory]
    [InlineData(766)]
    [InlineData(772)]
    public void SelectKnownPacks_Serverbound_TwoPacks_RoundTrips(int pv)
    {
        var packs = new[]
        {
            new KnownPack("minecraft", "core", "1.21"),
            new KnownPack("minecraft", "chat_type", "1.21"),
        };
        var p = new ConfigSb.SelectKnownPacksPacket(packs);
        var back = RoundTrip(p, pv);
        AssertPacksEqual(packs, back.Packs);
    }

    [Theory]
    [InlineData(766)]
    [InlineData(772)]
    public void SelectKnownPacks_Serverbound_EmptyArray_RoundTrips(int pv)
    {
        var p = new ConfigSb.SelectKnownPacksPacket([]);
        var back = RoundTrip(p, pv);
        Assert.Empty(back.Packs);
    }

    // ── Configuration ClientInformation ───────────────────────────────────────
    // Plain class, no value equality: compare field by field. @766 has 8 fields (no
    // ParticleStatus on the wire, so it is not compared); @772 adds ParticleStatus as a 9th field.

    [Fact]
    public void ClientInformation_766_8Fields_RoundTrips()
    {
        var p = new ConfigSb.ClientInformationPacket("en_us", 10, 0, true, 0x7F, 1, true, true);
        var back = RoundTrip(p, 766);

        Assert.Equal(p.Locale, back.Locale);
        Assert.Equal(p.ViewDistance, back.ViewDistance);
        Assert.Equal(p.ChatFlags, back.ChatFlags);
        Assert.Equal(p.ChatColors, back.ChatColors);
        Assert.Equal(p.SkinParts, back.SkinParts);
        Assert.Equal(p.MainHand, back.MainHand);
        Assert.Equal(p.EnableTextFiltering, back.EnableTextFiltering);
        Assert.Equal(p.EnableServerListing, back.EnableServerListing);
    }

    [Fact]
    public void ClientInformation_772_9Fields_RoundTrips()
    {
        var p = new ConfigSb.ClientInformationPacket("ru_ru", 32, 1, false, 0x3F, 0, false, true, V768_Last: new(2));
        var back = RoundTrip(p, 772);

        Assert.Equal(p.Locale, back.Locale);
        Assert.Equal(p.ViewDistance, back.ViewDistance);
        Assert.Equal(p.ChatFlags, back.ChatFlags);
        Assert.Equal(p.ChatColors, back.ChatColors);
        Assert.Equal(p.SkinParts, back.SkinParts);
        Assert.Equal(p.MainHand, back.MainHand);
        Assert.Equal(p.EnableTextFiltering, back.EnableTextFiltering);
        Assert.Equal(p.EnableServerListing, back.EnableServerListing);
        Assert.Equal(2, back.V768_Last?.ParticleStatus);
    }

    // Form-A contract: writing at a version whose layer group is not filled must throw, never
    // send a half-formed packet.
    [Fact]
    public void ClientInformation_772_WithoutLayer_ThrowsWrongLayer()
    {
        var p = new ConfigSb.ClientInformationPacket("en_us", 10, 0, true, 0x7F, 1, true, true);
        var writer = new MinecraftPrimitiveWriter();

        Assert.Throws<WrongLayerException>(() => p.Write(writer, 772));
    }

    // ── Configuration FinishConfiguration (empty packet) ──────────────────────

    [Fact]
    public void FinishConfiguration_Serverbound_764_RoundTrips()
    {
        var p = new ConfigSb.FinishConfigurationPacket();
        var back = RoundTrip(p, 764);
        Assert.Equal(p, back);
    }

    [Fact]
    public void FinishConfiguration_Clientbound_764_RoundTrips()
    {
        var p = new ConfigCb.FinishConfigurationPacket();
        var back = RoundTrip(p, 764);
        Assert.Equal(p, back);
    }

    // ── Play KeepAlive (serverbound) ──────────────────────────────────────────

    [Theory]
    [InlineData(735)]
    [InlineData(772)]
    public void PlayKeepAlive_Serverbound_RoundTrips(int pv)
    {
        var p = new PlaySb.KeepAlivePacket(555L);
        var back = RoundTrip(p, pv);
        Assert.Equal(p, back);
    }

    // ── Configuration Disconnect ───────────────────────────────────────────────

    [Fact]
    public void Disconnect_764_StringReason_RoundTrips()
    {
        var p = new ConfigCb.DisconnectPacket(V764: new("{\"text\":\"kicked\"}"));
        var back = RoundTrip(p, 764);
        Assert.Equal(p.V764?.ReasonJson, back.V764?.ReasonJson);
    }

    // Was skipped until 2026-08-13: the codegen's primitive table had the root-name flag inverted,
    // so an anonymousNbt field was read with a name and written without one. Fixed in
    // minecraft-protocol-fs (CSharpSurface.Primitives) and re-delivered; both sides now agree on
    // the nameless network root.
    [Fact]
    public void Disconnect_772_NbtReason_RoundTrips()
    {
        var reason = new NbtCompound("") { new NbtString("text", "Bye") };
        var p = new ConfigCb.DisconnectPacket(V765_Last: new(reason));
        var back = RoundTrip(p, 772);

        var backCompound = Assert.IsType<NbtCompound>(back.V765_Last?.Reason);
        Assert.Equal("Bye", backCompound.Get<NbtString>("text")!.Value);
    }

    // ── Login LoginStart: the artifact's showcase packet, four layers ─────────

    [Fact]
    public void LoginStart_758_CommonOnly_RoundTrips()
    {
        var p = new LoginSb.LoginStartPacket("TitleBot");
        var back = RoundTrip(p, 758);
        Assert.Equal("TitleBot", back.Username);
        Assert.Null(back.V764_Last);
    }

    [Fact]
    public void LoginStart_772_V764Layer_RoundTrips()
    {
        var uuid = Guid.NewGuid();
        var p = new LoginSb.LoginStartPacket("TitleBot", V764_Last: new(uuid));
        var back = RoundTrip(p, 772);

        Assert.Equal("TitleBot", back.Username);
        Assert.Equal(uuid, back.V764_Last?.PlayerUuid);
    }

    [Fact]
    public void LoginStart_772_WithoutLayer_ThrowsWrongLayer()
    {
        var p = new LoginSb.LoginStartPacket("TitleBot");
        var writer = new MinecraftPrimitiveWriter();

        Assert.Throws<WrongLayerException>(() => p.Write(writer, 772));
    }

    // ── FixedBytes: exactly-n bytes, no length prefix ────────────────────────

    private static PlaySb.ChatCommandSignedPacket ChatCommandSigned(byte[] acknowledged, int pv)
        => new(
            "gamemode creative",
            1_700_000_000_000L,
            -42L,
            [new ArgumentSignature("target", [.. Enumerable.Range(0, 256).Select(i => (byte)i)])],
            3,
            acknowledged,
            pv >= 770 ? new PlaySb.ChatCommandSignedPacket.V770_LastLayer(9) : null);

    [Theory]
    [InlineData(768)]
    [InlineData(772)]
    public void ChatCommandSigned_FixedBytes_RoundTrips(int pv)
    {
        var p = ChatCommandSigned([0xAA, 0xBB, 0xCC], pv);
        var back = RoundTrip(p, pv);

        Assert.Equal(p.Command, back.Command);
        Assert.Equal(p.Timestamp, back.Timestamp);
        Assert.Equal(p.Salt, back.Salt);
        Assert.Equal(p.MessageCount, back.MessageCount);
        Assert.Equal(p.Acknowledged, back.Acknowledged);
        Assert.Equal(p.V770_Last, back.V770_Last);
        Assert.Equal(256, back.ArgumentSignatures[0].Signature.Length);
        Assert.Equal(p.ArgumentSignatures[0].Signature, back.ArgumentSignatures[0].Signature);
    }

    [Theory]
    [InlineData(2)]
    [InlineData(4)]
    public void ChatCommandSigned_WrongFixedLength_Throws(int length)
    {
        var p = ChatCommandSigned(new byte[length], 772);

        Assert.Throws<ArgumentException>(() => p.Write(new MinecraftPrimitiveWriter(), 772));
    }

    [Fact]
    public void ChatCommandSigned_FixedBytes_ConsumesExactlyThreeBytes()
    {
        var p = ChatCommandSigned([1, 2, 3], 768);
        var writer = new MinecraftPrimitiveWriter();
        p.Write(writer, 768);
        using var mem = writer.GetWrittenMemory();

        // command + timestamp + salt + one signature + count + 3 acknowledged bytes, nothing else
        var expected = 1 + "gamemode creative".Length + 8 + 8
                       + 1 + 1 + "target".Length + 256
                       + 1 + 3;
        Assert.Equal(expected, mem.Memory.Length);
    }

    // ── GetPacketId vs the fs packet-id manifest (Spec/protocol-ids.json) ─────

    [Fact]
    public void GetPacketId_MatchesManifest()
    {
        Assert.Equal(0x01, ConfigCb.DisconnectPacket.GetPacketId(764));
        Assert.Equal(0x02, ConfigCb.DisconnectPacket.GetPacketId(772));

        Assert.Equal(0x02, ConfigCb.FinishConfigurationPacket.GetPacketId(764));
        Assert.Equal(0x02, ConfigSb.FinishConfigurationPacket.GetPacketId(764));
        Assert.Equal(0x03, ConfigSb.FinishConfigurationPacket.GetPacketId(766));

        Assert.Equal(0x03, ConfigCb.KeepAlivePacket.GetPacketId(764));
        Assert.Equal(0x04, ConfigCb.KeepAlivePacket.GetPacketId(772));
        Assert.Equal(0x03, ConfigSb.KeepAlivePacket.GetPacketId(764));
        Assert.Equal(0x04, ConfigSb.KeepAlivePacket.GetPacketId(772));

        Assert.Equal(0x0E, ConfigCb.SelectKnownPacksPacket.GetPacketId(766));
        Assert.Equal(0x0E, ConfigCb.SelectKnownPacksPacket.GetPacketId(772));
        Assert.Equal(0x07, ConfigSb.SelectKnownPacksPacket.GetPacketId(766));
        Assert.Equal(0x07, ConfigSb.SelectKnownPacksPacket.GetPacketId(772));

        Assert.Equal(0x00, ConfigSb.ClientInformationPacket.GetPacketId(766));
        Assert.Equal(0x00, ConfigSb.ClientInformationPacket.GetPacketId(772));

        Assert.Equal(0x10, PlaySb.KeepAlivePacket.GetPacketId(735));
        Assert.Equal(0x1B, PlaySb.KeepAlivePacket.GetPacketId(772));
    }
}
