using System.Collections.Frozen;

namespace McProtoNet.Protocol;

public static partial class PacketIdHelper
{
    private static FrozenDictionary<long, int> ClientboundHandshakingPackets =
        new Dictionary<long, int>().ToFrozenDictionary();

    private static FrozenDictionary<long, int> ServerboundHandshakingPackets = new Dictionary<long, int>
    {
        { Combine(ClientHandshakingPacket.SetProtocol, 340), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 340), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 351), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 351), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 393), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 393), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 401), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 401), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 402), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 402), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 403), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 403), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 404), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 404), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 477), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 477), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 480), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 480), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 490), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 490), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 498), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 498), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 573), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 573), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 575), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 575), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 578), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 578), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 709), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 709), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 710), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 710), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 734), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 734), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 735), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 735), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 736), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 736), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 751), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 751), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 753), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 753), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 754), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 754), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 755), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 755), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 756), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 756), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 757), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 757), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 758), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 758), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 759), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 759), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 760), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 760), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 761), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 761), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 762), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 762), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 763), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 763), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 764), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 764), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 765), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 765), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 766), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 766), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 767), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 767), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 768), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 768), 0xfe },
        { Combine(ClientHandshakingPacket.SetProtocol, 769), 0x00 },
        { Combine(ClientHandshakingPacket.LegacyServerListPing, 769), 0xfe },
    }.ToFrozenDictionary();
}