using System.Collections.Frozen;

namespace McProtoNet.Protocol;

public static partial class PacketIdHelper
{
    private static readonly Dictionary<(PacketIdentifier, int), int> clientboundConfigurationPackets =
        new()
        {
            { (ServerConfigurationPacket.CustomPayload, 764), 0x00 },
            { (ServerConfigurationPacket.Disconnect, 764), 0x01 },
            { (ServerConfigurationPacket.FinishConfiguration, 764), 0x02 },
            { (ServerConfigurationPacket.KeepAlive, 764), 0x03 },
            { (ServerConfigurationPacket.Ping, 764), 0x04 },
            { (ServerConfigurationPacket.RegistryData, 764), 0x05 },
            { (ServerConfigurationPacket.ResourcePackSend, 764), 0x06 },
            { (ServerConfigurationPacket.FeatureFlags, 764), 0x07 },
            { (ServerConfigurationPacket.Tags, 764), 0x08 },
            { (ServerConfigurationPacket.CustomPayload, 765), 0x00 },
            { (ServerConfigurationPacket.Disconnect, 765), 0x01 },
            { (ServerConfigurationPacket.FinishConfiguration, 765), 0x02 },
            { (ServerConfigurationPacket.KeepAlive, 765), 0x03 },
            { (ServerConfigurationPacket.Ping, 765), 0x04 },
            { (ServerConfigurationPacket.RegistryData, 765), 0x05 },
            { (ServerConfigurationPacket.RemoveResourcePack, 765), 0x06 },
            { (ServerConfigurationPacket.AddResourcePack, 765), 0x07 },
            { (ServerConfigurationPacket.FeatureFlags, 765), 0x08 },
            { (ServerConfigurationPacket.Tags, 765), 0x09 },
            { (ServerConfigurationPacket.CookieRequest, 766), 0x00 },
            { (ServerConfigurationPacket.CustomPayload, 766), 0x01 },
            { (ServerConfigurationPacket.Disconnect, 766), 0x02 },
            { (ServerConfigurationPacket.FinishConfiguration, 766), 0x03 },
            { (ServerConfigurationPacket.KeepAlive, 766), 0x04 },
            { (ServerConfigurationPacket.Ping, 766), 0x05 },
            { (ServerConfigurationPacket.ResetChat, 766), 0x06 },
            { (ServerConfigurationPacket.RegistryData, 766), 0x07 },
            { (ServerConfigurationPacket.RemoveResourcePack, 766), 0x08 },
            { (ServerConfigurationPacket.AddResourcePack, 766), 0x09 },
            { (ServerConfigurationPacket.StoreCookie, 766), 0x0a },
            { (ServerConfigurationPacket.Transfer, 766), 0x0b },
            { (ServerConfigurationPacket.FeatureFlags, 766), 0x0c },
            { (ServerConfigurationPacket.Tags, 766), 0x0d },
            { (ServerConfigurationPacket.SelectKnownPacks, 766), 0x0e },
            { (ServerConfigurationPacket.CookieRequest, 767), 0x00 },
            { (ServerConfigurationPacket.CustomPayload, 767), 0x01 },
            { (ServerConfigurationPacket.Disconnect, 767), 0x02 },
            { (ServerConfigurationPacket.FinishConfiguration, 767), 0x03 },
            { (ServerConfigurationPacket.KeepAlive, 767), 0x04 },
            { (ServerConfigurationPacket.Ping, 767), 0x05 },
            { (ServerConfigurationPacket.ResetChat, 767), 0x06 },
            { (ServerConfigurationPacket.RegistryData, 767), 0x07 },
            { (ServerConfigurationPacket.RemoveResourcePack, 767), 0x08 },
            { (ServerConfigurationPacket.AddResourcePack, 767), 0x09 },
            { (ServerConfigurationPacket.StoreCookie, 767), 0x0a },
            { (ServerConfigurationPacket.Transfer, 767), 0x0b },
            { (ServerConfigurationPacket.FeatureFlags, 767), 0x0c },
            { (ServerConfigurationPacket.Tags, 767), 0x0d },
            { (ServerConfigurationPacket.SelectKnownPacks, 767), 0x0e },
            { (ServerConfigurationPacket.CustomReportDetails, 767), 0x0f },
            { (ServerConfigurationPacket.ServerLinks, 767), 0x10 },
            { (ServerConfigurationPacket.CookieRequest, 768), 0x00 },
            { (ServerConfigurationPacket.CustomPayload, 768), 0x01 },
            { (ServerConfigurationPacket.Disconnect, 768), 0x02 },
            { (ServerConfigurationPacket.FinishConfiguration, 768), 0x03 },
            { (ServerConfigurationPacket.KeepAlive, 768), 0x04 },
            { (ServerConfigurationPacket.Ping, 768), 0x05 },
            { (ServerConfigurationPacket.ResetChat, 768), 0x06 },
            { (ServerConfigurationPacket.RegistryData, 768), 0x07 },
            { (ServerConfigurationPacket.RemoveResourcePack, 768), 0x08 },
            { (ServerConfigurationPacket.AddResourcePack, 768), 0x09 },
            { (ServerConfigurationPacket.StoreCookie, 768), 0x0a },
            { (ServerConfigurationPacket.Transfer, 768), 0x0b },
            { (ServerConfigurationPacket.FeatureFlags, 768), 0x0c },
            { (ServerConfigurationPacket.Tags, 768), 0x0d },
            { (ServerConfigurationPacket.SelectKnownPacks, 768), 0x0e },
            { (ServerConfigurationPacket.CustomReportDetails, 768), 0x0f },
            { (ServerConfigurationPacket.ServerLinks, 768), 0x10 },
            { (ServerConfigurationPacket.CookieRequest, 769), 0x00 },
            { (ServerConfigurationPacket.CustomPayload, 769), 0x01 },
            { (ServerConfigurationPacket.Disconnect, 769), 0x02 },
            { (ServerConfigurationPacket.FinishConfiguration, 769), 0x03 },
            { (ServerConfigurationPacket.KeepAlive, 769), 0x04 },
            { (ServerConfigurationPacket.Ping, 769), 0x05 },
            { (ServerConfigurationPacket.ResetChat, 769), 0x06 },
            { (ServerConfigurationPacket.RegistryData, 769), 0x07 },
            { (ServerConfigurationPacket.RemoveResourcePack, 769), 0x08 },
            { (ServerConfigurationPacket.AddResourcePack, 769), 0x09 },
            { (ServerConfigurationPacket.StoreCookie, 769), 0x0a },
            { (ServerConfigurationPacket.Transfer, 769), 0x0b },
            { (ServerConfigurationPacket.FeatureFlags, 769), 0x0c },
            { (ServerConfigurationPacket.Tags, 769), 0x0d },
            { (ServerConfigurationPacket.SelectKnownPacks, 769), 0x0e },
            { (ServerConfigurationPacket.CustomReportDetails, 769), 0x0f },
            { (ServerConfigurationPacket.ServerLinks, 769), 0x10 },
        };

    private static readonly Dictionary<(PacketIdentifier, int), int> serverboundConfigurationPackets =
        new()
        {
            { (ClientConfigurationPacket.Settings, 764), 0x00 },
            { (ClientConfigurationPacket.CustomPayload, 764), 0x01 },
            { (ClientConfigurationPacket.FinishConfiguration, 764), 0x02 },
            { (ClientConfigurationPacket.KeepAlive, 764), 0x03 },
            { (ClientConfigurationPacket.Pong, 764), 0x04 },
            { (ClientConfigurationPacket.ResourcePackReceive, 764), 0x05 },
            { (ClientConfigurationPacket.Settings, 765), 0x00 },
            { (ClientConfigurationPacket.CustomPayload, 765), 0x01 },
            { (ClientConfigurationPacket.FinishConfiguration, 765), 0x02 },
            { (ClientConfigurationPacket.KeepAlive, 765), 0x03 },
            { (ClientConfigurationPacket.Pong, 765), 0x04 },
            { (ClientConfigurationPacket.ResourcePackReceive, 765), 0x05 },
            { (ClientConfigurationPacket.Settings, 766), 0x00 },
            { (ClientConfigurationPacket.CookieResponse, 766), 0x01 },
            { (ClientConfigurationPacket.CustomPayload, 766), 0x02 },
            { (ClientConfigurationPacket.FinishConfiguration, 766), 0x03 },
            { (ClientConfigurationPacket.KeepAlive, 766), 0x04 },
            { (ClientConfigurationPacket.Pong, 766), 0x05 },
            { (ClientConfigurationPacket.ResourcePackReceive, 766), 0x06 },
            { (ClientConfigurationPacket.SelectKnownPacks, 766), 0x07 },
            { (ClientConfigurationPacket.Settings, 767), 0x00 },
            { (ClientConfigurationPacket.CookieResponse, 767), 0x01 },
            { (ClientConfigurationPacket.CustomPayload, 767), 0x02 },
            { (ClientConfigurationPacket.FinishConfiguration, 767), 0x03 },
            { (ClientConfigurationPacket.KeepAlive, 767), 0x04 },
            { (ClientConfigurationPacket.Pong, 767), 0x05 },
            { (ClientConfigurationPacket.ResourcePackReceive, 767), 0x06 },
            { (ClientConfigurationPacket.SelectKnownPacks, 767), 0x07 },
            { (ClientConfigurationPacket.CustomReportDetails, 767), 0x08 },
            { (ClientConfigurationPacket.ServerLinks, 767), 0x09 },
            { (ClientConfigurationPacket.Settings, 768), 0x00 },
            { (ClientConfigurationPacket.CookieResponse, 768), 0x01 },
            { (ClientConfigurationPacket.CustomPayload, 768), 0x02 },
            { (ClientConfigurationPacket.FinishConfiguration, 768), 0x03 },
            { (ClientConfigurationPacket.KeepAlive, 768), 0x04 },
            { (ClientConfigurationPacket.Pong, 768), 0x05 },
            { (ClientConfigurationPacket.ResourcePackReceive, 768), 0x06 },
            { (ClientConfigurationPacket.SelectKnownPacks, 768), 0x07 },
            { (ClientConfigurationPacket.CustomReportDetails, 768), 0x08 },
            { (ClientConfigurationPacket.ServerLinks, 768), 0x09 },
            { (ClientConfigurationPacket.Settings, 769), 0x00 },
            { (ClientConfigurationPacket.CookieResponse, 769), 0x01 },
            { (ClientConfigurationPacket.CustomPayload, 769), 0x02 },
            { (ClientConfigurationPacket.FinishConfiguration, 769), 0x03 },
            { (ClientConfigurationPacket.KeepAlive, 769), 0x04 },
            { (ClientConfigurationPacket.Pong, 769), 0x05 },
            { (ClientConfigurationPacket.ResourcePackReceive, 769), 0x06 },
            { (ClientConfigurationPacket.SelectKnownPacks, 769), 0x07 },
            { (ClientConfigurationPacket.CustomReportDetails, 769), 0x08 },
            { (ClientConfigurationPacket.ServerLinks, 769), 0x09 },
        };

    private static readonly FrozenDictionary<long, int> ClientboundConfigurationPackets =
        CombineAll(clientboundConfigurationPackets);

    private static readonly FrozenDictionary<long, int> ServerboundConfigurationPackets =
        CombineAll(serverboundConfigurationPackets);
}