using System.Collections.Frozen;

namespace McProtoNet.Protocol;

public static partial class PacketIdHelper
{
    private static readonly Dictionary<(PacketIdentifier, int), int> clientboundStatusPackets =
        new()
        {
            { (ServerStatusPacket.ServerInfo, 340), 0x00 },
            { (ServerStatusPacket.Ping, 340), 0x01 },
            { (ServerStatusPacket.ServerInfo, 351), 0x00 },
            { (ServerStatusPacket.Ping, 351), 0x01 },
            { (ServerStatusPacket.ServerInfo, 393), 0x00 },
            { (ServerStatusPacket.Ping, 393), 0x01 },
            { (ServerStatusPacket.ServerInfo, 401), 0x00 },
            { (ServerStatusPacket.Ping, 401), 0x01 },
            { (ServerStatusPacket.ServerInfo, 402), 0x00 },
            { (ServerStatusPacket.Ping, 402), 0x01 },
            { (ServerStatusPacket.ServerInfo, 403), 0x00 },
            { (ServerStatusPacket.Ping, 403), 0x01 },
            { (ServerStatusPacket.ServerInfo, 404), 0x00 },
            { (ServerStatusPacket.Ping, 404), 0x01 },
            { (ServerStatusPacket.ServerInfo, 477), 0x00 },
            { (ServerStatusPacket.Ping, 477), 0x01 },
            { (ServerStatusPacket.ServerInfo, 480), 0x00 },
            { (ServerStatusPacket.Ping, 480), 0x01 },
            { (ServerStatusPacket.ServerInfo, 490), 0x00 },
            { (ServerStatusPacket.Ping, 490), 0x01 },
            { (ServerStatusPacket.ServerInfo, 498), 0x00 },
            { (ServerStatusPacket.Ping, 498), 0x01 },
            { (ServerStatusPacket.ServerInfo, 573), 0x00 },
            { (ServerStatusPacket.Ping, 573), 0x01 },
            { (ServerStatusPacket.ServerInfo, 575), 0x00 },
            { (ServerStatusPacket.Ping, 575), 0x01 },
            { (ServerStatusPacket.ServerInfo, 578), 0x00 },
            { (ServerStatusPacket.Ping, 578), 0x01 },
            { (ServerStatusPacket.ServerInfo, 709), 0x00 },
            { (ServerStatusPacket.Ping, 709), 0x01 },
            { (ServerStatusPacket.ServerInfo, 710), 0x00 },
            { (ServerStatusPacket.Ping, 710), 0x01 },
            { (ServerStatusPacket.ServerInfo, 734), 0x00 },
            { (ServerStatusPacket.Ping, 734), 0x01 },
            { (ServerStatusPacket.ServerInfo, 735), 0x00 },
            { (ServerStatusPacket.Ping, 735), 0x01 },
            { (ServerStatusPacket.ServerInfo, 736), 0x00 },
            { (ServerStatusPacket.Ping, 736), 0x01 },
            { (ServerStatusPacket.ServerInfo, 751), 0x00 },
            { (ServerStatusPacket.Ping, 751), 0x01 },
            { (ServerStatusPacket.ServerInfo, 753), 0x00 },
            { (ServerStatusPacket.Ping, 753), 0x01 },
            { (ServerStatusPacket.ServerInfo, 754), 0x00 },
            { (ServerStatusPacket.Ping, 754), 0x01 },
            { (ServerStatusPacket.ServerInfo, 755), 0x00 },
            { (ServerStatusPacket.Ping, 755), 0x01 },
            { (ServerStatusPacket.ServerInfo, 756), 0x00 },
            { (ServerStatusPacket.Ping, 756), 0x01 },
            { (ServerStatusPacket.ServerInfo, 757), 0x00 },
            { (ServerStatusPacket.Ping, 757), 0x01 },
            { (ServerStatusPacket.ServerInfo, 758), 0x00 },
            { (ServerStatusPacket.Ping, 758), 0x01 },
            { (ServerStatusPacket.ServerInfo, 759), 0x00 },
            { (ServerStatusPacket.Ping, 759), 0x01 },
            { (ServerStatusPacket.ServerInfo, 760), 0x00 },
            { (ServerStatusPacket.Ping, 760), 0x01 },
            { (ServerStatusPacket.ServerInfo, 761), 0x00 },
            { (ServerStatusPacket.Ping, 761), 0x01 },
            { (ServerStatusPacket.ServerInfo, 762), 0x00 },
            { (ServerStatusPacket.Ping, 762), 0x01 },
            { (ServerStatusPacket.ServerInfo, 763), 0x00 },
            { (ServerStatusPacket.Ping, 763), 0x01 },
            { (ServerStatusPacket.ServerInfo, 764), 0x00 },
            { (ServerStatusPacket.Ping, 764), 0x01 },
            { (ServerStatusPacket.ServerInfo, 765), 0x00 },
            { (ServerStatusPacket.Ping, 765), 0x01 },
            { (ServerStatusPacket.ServerInfo, 766), 0x00 },
            { (ServerStatusPacket.Ping, 766), 0x01 },
            { (ServerStatusPacket.ServerInfo, 767), 0x00 },
            { (ServerStatusPacket.Ping, 767), 0x01 },
            { (ServerStatusPacket.ServerInfo, 768), 0x00 },
            { (ServerStatusPacket.Ping, 768), 0x01 },
            { (ServerStatusPacket.ServerInfo, 769), 0x00 },
            { (ServerStatusPacket.Ping, 769), 0x01 },
        };

    private static readonly Dictionary<(PacketIdentifier, int), int> serverboundStatusPackets =
        new()
        {
            { (ClientStatusPacket.PingStart, 340), 0x00 },
            { (ClientStatusPacket.Ping, 340), 0x01 },
            { (ClientStatusPacket.PingStart, 351), 0x00 },
            { (ClientStatusPacket.Ping, 351), 0x01 },
            { (ClientStatusPacket.PingStart, 393), 0x00 },
            { (ClientStatusPacket.Ping, 393), 0x01 },
            { (ClientStatusPacket.PingStart, 401), 0x00 },
            { (ClientStatusPacket.Ping, 401), 0x01 },
            { (ClientStatusPacket.PingStart, 402), 0x00 },
            { (ClientStatusPacket.Ping, 402), 0x01 },
            { (ClientStatusPacket.PingStart, 403), 0x00 },
            { (ClientStatusPacket.Ping, 403), 0x01 },
            { (ClientStatusPacket.PingStart, 404), 0x00 },
            { (ClientStatusPacket.Ping, 404), 0x01 },
            { (ClientStatusPacket.PingStart, 477), 0x00 },
            { (ClientStatusPacket.Ping, 477), 0x01 },
            { (ClientStatusPacket.PingStart, 480), 0x00 },
            { (ClientStatusPacket.Ping, 480), 0x01 },
            { (ClientStatusPacket.PingStart, 490), 0x00 },
            { (ClientStatusPacket.Ping, 490), 0x01 },
            { (ClientStatusPacket.PingStart, 498), 0x00 },
            { (ClientStatusPacket.Ping, 498), 0x01 },
            { (ClientStatusPacket.PingStart, 573), 0x00 },
            { (ClientStatusPacket.Ping, 573), 0x01 },
            { (ClientStatusPacket.PingStart, 575), 0x00 },
            { (ClientStatusPacket.Ping, 575), 0x01 },
            { (ClientStatusPacket.PingStart, 578), 0x00 },
            { (ClientStatusPacket.Ping, 578), 0x01 },
            { (ClientStatusPacket.PingStart, 709), 0x00 },
            { (ClientStatusPacket.Ping, 709), 0x01 },
            { (ClientStatusPacket.PingStart, 710), 0x00 },
            { (ClientStatusPacket.Ping, 710), 0x01 },
            { (ClientStatusPacket.PingStart, 734), 0x00 },
            { (ClientStatusPacket.Ping, 734), 0x01 },
            { (ClientStatusPacket.PingStart, 735), 0x00 },
            { (ClientStatusPacket.Ping, 735), 0x01 },
            { (ClientStatusPacket.PingStart, 736), 0x00 },
            { (ClientStatusPacket.Ping, 736), 0x01 },
            { (ClientStatusPacket.PingStart, 751), 0x00 },
            { (ClientStatusPacket.Ping, 751), 0x01 },
            { (ClientStatusPacket.PingStart, 753), 0x00 },
            { (ClientStatusPacket.Ping, 753), 0x01 },
            { (ClientStatusPacket.PingStart, 754), 0x00 },
            { (ClientStatusPacket.Ping, 754), 0x01 },
            { (ClientStatusPacket.PingStart, 755), 0x00 },
            { (ClientStatusPacket.Ping, 755), 0x01 },
            { (ClientStatusPacket.PingStart, 756), 0x00 },
            { (ClientStatusPacket.Ping, 756), 0x01 },
            { (ClientStatusPacket.PingStart, 757), 0x00 },
            { (ClientStatusPacket.Ping, 757), 0x01 },
            { (ClientStatusPacket.PingStart, 758), 0x00 },
            { (ClientStatusPacket.Ping, 758), 0x01 },
            { (ClientStatusPacket.PingStart, 759), 0x00 },
            { (ClientStatusPacket.Ping, 759), 0x01 },
            { (ClientStatusPacket.PingStart, 760), 0x00 },
            { (ClientStatusPacket.Ping, 760), 0x01 },
            { (ClientStatusPacket.PingStart, 761), 0x00 },
            { (ClientStatusPacket.Ping, 761), 0x01 },
            { (ClientStatusPacket.PingStart, 762), 0x00 },
            { (ClientStatusPacket.Ping, 762), 0x01 },
            { (ClientStatusPacket.PingStart, 763), 0x00 },
            { (ClientStatusPacket.Ping, 763), 0x01 },
            { (ClientStatusPacket.PingStart, 764), 0x00 },
            { (ClientStatusPacket.Ping, 764), 0x01 },
            { (ClientStatusPacket.PingStart, 765), 0x00 },
            { (ClientStatusPacket.Ping, 765), 0x01 },
            { (ClientStatusPacket.PingStart, 766), 0x00 },
            { (ClientStatusPacket.Ping, 766), 0x01 },
            { (ClientStatusPacket.PingStart, 767), 0x00 },
            { (ClientStatusPacket.Ping, 767), 0x01 },
            { (ClientStatusPacket.PingStart, 768), 0x00 },
            { (ClientStatusPacket.Ping, 768), 0x01 },
            { (ClientStatusPacket.PingStart, 769), 0x00 },
            { (ClientStatusPacket.Ping, 769), 0x01 },
        };

    private static readonly FrozenDictionary<long, int> ClientboundStatusPackets = CombineAll(clientboundStatusPackets);
    private static readonly FrozenDictionary<long, int> ServerboundStatusPackets = CombineAll(serverboundStatusPackets);
}