<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <PropertyGroup>
    <RepositoryUrl>https://github.com/Titlehhhh/McProtoNet</RepositoryUrl>
    <PackageTags>minecraft;protocol;high-performance</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://titlehhhh.github.io/McProtoNet</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <Authors>Titlehhhh</Authors>
    <Copyright>Copyright 2022-$([System.DateTime]::Now.ToString(`yyyy`)) © Titlehhhh</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerDefaultPreReleaseIdentifiers>dev.0</MinVerDefaultPreReleaseIdentifiers>
  </PropertyGroup>
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Readme.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup Label="PackageIcon">
    <None Include="$(MSBuildThisFileDirectory)/assets/icon.png" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup>
    <EnableSourceLink>true</EnableSourceLink>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591;CS0535</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Dunet" Version="1.16.2" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="McProtoNet.Native" Version="1.0.0" />
    <PackageVersion Include="System.IO.Pipelines" Version="10.0.11" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>
</Project>
