<Project>
  <PropertyGroup>
    <MSBuildEnableWorkloadResolver>false</MSBuildEnableWorkloadResolver>
    <UseSharedCompilation>false</UseSharedCompilation>
    <RestoreFallbackFolders></RestoreFallbackFolders>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
</Project>
