name: cicd.yaml
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release/*
    tags:
      - "v*"
    paths-ignore:
      - 'docs/**'
      - 'README.md'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Run tests
        run: dotnet run --project tests/McProtoNet.Tests -c Release

  tests-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Run crypto tests on ARM64
        run: dotnet run --project tests/McProtoNet.Tests -c Release -- -namespace McProtoNet.Tests.Cryptography

  publish-nuget:
    if: ${{ github.event_name == 'push' }}
    needs: [tests, tests-arm64]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          
      - name: Feedz push
        run: ./build.cmd Push --Configuration Release --skip Tests --NugetApiUrl https://f.feedz.io/mcprotonet/night/nuget/index.json --NugetApiKey ${{secrets.FEEDZ_TOKEN}}
      
      - name: Nuget push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./build.cmd Push --Configuration Release --skip Tests --NugetApiUrl https://api.nuget.org/v3/index.json --NugetApiKey ${{secrets.NUGET_TOKEN}}