name: publish-manual
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Feed to push to"
        required: true
        type: choice
        options:
          - feedz
          - nuget
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x
            11.0.x
          dotnet-quality: preview
      - name: Push to feedz
        if: ${{ inputs.target == 'feedz' }}
        run: ./build.cmd Push --Configuration Release --NugetApiUrl https://f.feedz.io/mcprotonet/night/nuget/index.json --NugetApiKey ${{secrets.FEEDZ_TOKEN}}
      - name: Push to nuget.org
        if: ${{ inputs.target == 'nuget' && startsWith(github.ref, 'refs/tags/v') }}
        run: ./build.cmd Push --Configuration Release --NugetApiUrl https://api.nuget.org/v3/index.json --NugetApiKey ${{secrets.NUGET_TOKEN}}
      - name: Upload packages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: artifacts/nuget/*.nupkg
          retention-days: 14
          if-no-files-found: ignore
